# Generated by Django 3.2.9 on 2021-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenstorage',
            name='QR',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tokenstorage',
            name='privatekey',
            field=models.FileField(upload_to=''),
        ),
    ]
