# Generated by Django 3.2.9 on 2021-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penut', '0002_auto_20211116_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenstorage',
            name='QR',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='tokenstorage',
            name='privatekey',
            field=models.BinaryField(),
        ),
    ]
